# data_config.py
# Feature options must match the exact values used during model training.
# If your label_encoders.pkl has different classes, update these lists to match.

FEATURE_OPTIONS = {
    "Day_of_week": ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    "Age_band_of_driver": ['Under 18', '18-30', '31-50', 'Over 51', 'Unknown'],
    "Sex_of_driver": ['Female', 'Male', 'Unknown'],
    "Vehicle_driver_relation": ['Employee', 'Other', 'Owner', 'Unknown'],
    "Driving_experience": ['Below 1yr', '1-2yr', '2-5yr', '5-10yr', 'Above 10yr', 'No Licence', 'unknown'],
    "Type_of_vehicle": ['Automobile', 'Bajaj', 'Bicycle', 'Long lorry', 'Lorry (11?40Q)', 'Lorry (41?100Q)', 'Motorcycle', 'Other', 'Pick up upto 10Q', 'Public (12 seats)', 'Public (13?45 seats)', 'Public (> 45 seats)', 'Ridden horse', 'Special vehicle', 'Stationwagen', 'Taxi', 'Turbo'],
    "Owner_of_vehicle": ['Governmental', 'Organization', 'Owner', 'Other'],
    "Defect_of_vehicle": ['No defect', 'Brake defect', 'Tire defect'],
    "Area_accident_occured": ['Church areas', 'Hospital areas', 'Industrial areas', 'Market areas', 'Office areas', 'Outside rural areas', 'Recreational areas', 'Residential areas', 'Rural village areas', 'School areas', 'Other', 'Unknown'],
    "Lanes_or_Medians": ['Double carriageway (median)', 'One way', 'Two-way (divided with broken lines road marking)', 'Two-way (divided with solid lines road marking)', 'Undivided Two way', 'Unknown', 'other'],
    "Road_allignment": ['Escarpments', 'Gentle horizontal curve', 'Sharp reverse curve', 'Steep grade downward with mountainous terrain', 'Steep grade upward with mountainous terrain', 'Tangent road with flat terrain', 'Tangent road with mild grade and flat terrain', 'Tangent road with mountainous terrain and', 'Tangent road with rolling terrain'],
    "Types_of_Junction": ['Crossing', 'No junction', 'O Shape', 'Other', 'T Shape', 'X Shape', 'Y Shape', 'Unknown'],
    "Road_surface_type": ['Asphalt roads', 'Asphalt roads with some distress', 'Earth roads', 'Gravel roads', 'Other'],
    "Road_surface_conditions": ['Dry', 'Flood over 3cm. deep', 'Snow', 'Wet or damp'],
    "Light_conditions": ['Darkness - lights lit', 'Darkness - lights unlit', 'Darkness - no lighting', 'Daylight'],
    "Weather_conditions": ['Cloudy', 'Fog or mist', 'Normal', 'Raining', 'Raining and Windy', 'Snow', 'Windy', 'Other', 'Unknown'],
    "Type_of_collision": ['Collision with animals', 'Collision with pedestrians', 'Collision with roadside objects', 'Collision with roadside-parked vehicles', 'Fall from vehicles', 'Rollover', 'Vehicle with vehicle collision', 'With Train', 'Other', 'Unknown'],
    "Number_of_vehicles_involved": list(range(1, 8)),
    "Vehicle_movement": ['Entering a junction', 'Getting off', 'Going straight', 'Moving Backward', 'Overtaking', 'Parked', 'Reversing', 'Stopping', 'Turnover', 'U-Turn', 'Waiting to go', 'Other', 'Unknown'],
    "Fitness_of_casuality": ['Blind', 'Deaf', 'Normal', 'Other'],
    "Pedestrian_movement": ["Crossing from driver's nearside", 'Crossing from nearside - masked by parked or statioNot a Pedestrianry vehicle', 'Crossing from offside - masked by parked or statioNot a Pedestrianry vehicle', 'In carriageway, statioNot a Pedestrianry - not crossing (standing or playing)', 'In carriageway, statioNot a Pedestrianry - not crossing (standing or playing) - masked by parked or statioNot a Pedestrianry vehicle', 'Not a Pedestrian', 'Walking along in carriageway, back to traffic', 'Walking along in carriageway, facing traffic', 'Unknown or other'],
    "Cause_of_accident": ['Changing lane to the left', 'Changing lane to the right', 'Driving at high speed', 'Driving carelessly', 'Driving to the left', 'Driving under the influence of drugs', 'Drunk driving', 'Getting off the vehicle improperly', 'Improper parking', 'Moving Backward', 'No distancing', 'No priority to pedestrian', 'No priority to vehicle', 'Overloading', 'Overspeed', 'Overtaking', 'Overturning', 'Turnover', 'Other', 'Unknown'],
}

FEATURE_LABELS = {
    "Day_of_week": "Day of Week",
    "Age_band_of_driver": "Driver Age Band",
    "Sex_of_driver": "Driver Gender",
    "Vehicle_driver_relation": "Driver-Vehicle Relation",
    "Driving_experience": "Driving Experience",
    "Type_of_vehicle": "Type of Vehicle",
    "Owner_of_vehicle": "Vehicle Ownership",
    "Defect_of_vehicle": "Vehicle Defect",
    "Area_accident_occured": "Area of Accident",
    "Lanes_or_Medians": "Lanes / Medians",
    "Road_allignment": "Road Alignment",
    "Types_of_Junction": "Type of Junction",
    "Road_surface_type": "Road Surface Type",
    "Road_surface_conditions": "Road Surface Condition",
    "Light_conditions": "Light Conditions",
    "Weather_conditions": "Weather Conditions",
    "Type_of_collision": "Type of Collision",
    "Number_of_vehicles_involved": "Number of Vehicles",
    "Vehicle_movement": "Vehicle Movement",
    "Fitness_of_casuality": "Fitness of Casualty",
    "Pedestrian_movement": "Pedestrian Movement",
    "Cause_of_accident": "Cause of Accident",
}

# Order of features fed to the model — must match training feature order exactly.
DEFAULT_FEATURE_ORDER = [
    "Day_of_week",
    "Age_band_of_driver",
    "Sex_of_driver",
    "Vehicle_driver_relation",
    "Driving_experience",
    "Type_of_vehicle",
    "Owner_of_vehicle",
    "Defect_of_vehicle",
    "Area_accident_occured",
    "Lanes_or_Medians",
    "Road_allignment",
    "Types_of_Junction",
    "Road_surface_type",
    "Road_surface_conditions",
    "Light_conditions",
    "Weather_conditions",
    "Type_of_collision",
    "Number_of_vehicles_involved",
    "Vehicle_movement",
    "Fitness_of_casuality",
    "Pedestrian_movement",
    "Cause_of_accident"
]
